import { Account, AccountType, Currency } from './type';

export const mockAccounts: Account[] = [
  {
    id: '2',
    userId: 'user1',
    name: 'Payment',
    type: AccountType.Payment,
    currency: Currency.USD,
    balance: 9000,
    parentId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    children: [
      {
        id: '21',
        userId: 'user1',
        name: 'Checking Account',
        type: AccountType.Payment,
        currency: Currency.USD,
        balance: 5000,
        parentId: '2',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '22',
        userId: 'user1',
        name: 'Cash Wallet',
        type: AccountType.Payment,
        currency: Currency.USD,
        balance: 4000,
        parentId: '2',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
  {
    id: '3',
    userId: 'user1',
    name: 'Saving',
    type: AccountType.Saving,
    currency: Currency.USD,
    balance: 10000,
    parentId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    children: [
      {
        id: '31',
        userId: 'user1',
        name: 'Emergency Fund',
        type: AccountType.Saving,
        currency: Currency.USD,
        balance: 6000,
        parentId: '3',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '32',
        userId: 'user1',
        name: 'Vacation Fund',
        type: AccountType.Saving,
        currency: Currency.USD,
        balance: 4000,
        parentId: '3',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
  {
    id: '5',
    userId: 'user1',
    name: 'Lending',
    type: AccountType.Lending,
    currency: Currency.USD,
    balance: 20000,
    parentId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    children: [
      {
        id: '51',
        userId: 'user1',
        name: 'Personal Loan',
        type: AccountType.Lending,
        currency: Currency.USD,
        balance: 15000,
        parentId: '5',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '52',
        userId: 'user1',
        name: 'Friend Loan',
        type: AccountType.Lending,
        currency: Currency.USD,
        balance: 5000,
        parentId: '5',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
  {
    id: '6',
    userId: 'user1',
    name: 'Credit Card',
    type: AccountType.CreditCard,
    currency: Currency.USD,
    balance: -29000,
    parentId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    children: [
      {
        id: '61',
        userId: 'user1',
        name: 'Visa Card',
        type: AccountType.CreditCard,
        currency: Currency.USD,
        balance: -15000,
        parentId: '6',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '62',
        userId: 'user1',
        name: 'Mastercard',
        type: AccountType.CreditCard,
        currency: Currency.USD,
        balance: -14000,
        parentId: '6',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
  {
    id: '7',
    userId: 'user1',
    name: 'Debt',
    type: AccountType.Debt,
    currency: Currency.USD,
    balance: -80000,
    parentId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    children: [
      {
        id: '71',
        userId: 'user1',
        name: 'Mortgage',
        type: AccountType.Debt,
        currency: Currency.USD,
        balance: -70000,
        parentId: '7',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '72',
        userId: 'user1',
        name: 'Car Loan',
        type: AccountType.Debt,
        currency: Currency.USD,
        balance: -10000,
        parentId: '7',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
];
