export enum FeatureFlags {
  CATEGORY_FEATURE = 'CAT_SETTING',
  TRANSACTION_FEATURE = 'TRANX',
  PARTNER_FEATURE = 'PART_SETTING',
  PRODUCT_FEATURE = 'PROD_SETTING',
  ACCOUNT_FEATURE = 'ACC',
  BUDGET_CONTROL = 'BUDGET_CONTROL',
  FINANCE_REPORT = 'FINANCE_REPORT',
  WALLET_FEATURE = 'WALLET',
  EXCHANGE_RATE_FEATURE = 'EXCHANGE_RATE',
  MEMBERSHIP_FEATURE = 'MEMBERSHIP',
}
