export enum FeatureFlags {
  CATEGORY_FEATURE = 'CAT_SETTING',
  TRANSACTION_FEATURE = 'TRANX',
  PARTNER_FEATURE = 'PART_SETTING',
  PRODUCT_FEATURE = 'PROD_SETTING',
  ACCOUNT_FEATURE = 'ACC',
  BUDGET_FEATURE = 'BUDGET_CONTROL',
  FINANCE_FEATURE = 'FINANCE_REPORT',
  WALLET_FEATURE = 'WALLET',
  EXCHANGE_RATE_FEATURE = 'EXCHANGE_RATE',
  MEMBERSHIP_FEATURE = 'MEMBERSHIP',
  FAQ_FEATURE = 'FAQs',
}

export const USER_ROLES = {
  ADMIN: 'Admin',
  USER: 'User',
  CS: 'CS',
} as const;
